### ISSUE TITLE
Filtering with sub-notebooks

### ISSUE THREAD

**Issue by MsgtGreer** [CalebJohn/joplin-inline-todo#19] opened 2023-01-16 09:06 UTC
I have multiple notebooks, for every of them I have a TODO Summary filtered by the new feature you introduced. Very neat by the way, thank you very much.
But it seems to me, that it does not include child notebooks, is that true? Is there a way to filter recursively? I think that would be very helpful.

**Comment by MsgtGreer** [comment] 2023-01-20 08:12
I looked at how you parse a list of notebook names. I think that using the API it should be possible to add child folders to the list of parsed notebook names, when the parser encounters something like a '/*'. I am considering bodging together something in that regard. Will see if i manage over the weekend. My JS is weak though.

**Comment by CalebJohn** [comment] 2023-10-18 21:49
I believe this is a duplicate of #18. I plan to implement the syntax from there, so I will close this one.

**Closed by CalebJohn** 2023-10-18 21:49 UTC
